### ISSUE TITLE
adding drugs

### ISSUE THREAD

**Issue by crixzgamez** [MacieGx/esx_planting#2] opened 2019-04-26 02:48 UTC
Hi, could u pls explain to me a little further on how to add more drugs to this list?
Ive sat for 2 hours trying to do it different, Ill past my pastebin so u can tell me whats wrong.
Im just using the same animations+questions etc as I tried to change it but didnt get it to work.
https://pastebin.com/2tAfK2wE
as of said Ive tried many different variants, but every time I attempt with another drug I get errors in the console.
Any help is appreciated

**Comment by crixzgamez** [comment] 2019-04-26 14:51
esx_planting - server - main.lua
seed_weed is called in this script,
I duped the script so I had 
esx_planting1 and changed the main.lua to ex: coke_mix
same with the config file, i changed the name to coke_mix
and added coke_mix to db item table.
This way I managed to add more drugs, but as of said I can not get it to work in the same script.
Can you help? :)

**Comment by MacieGx** [comment] 2019-04-27 12:43
You don't need to copy resource and start two resources at once if you want add more drugs or other plants.

The thing that you need is just have a good configuration inside config.lua.
I was saw your file by pastebin and notice that you did it wrong
You forgot to add some closed tags "}", and also did it wrong way. (~103 line)

Should be like that:
`options = {
    ["first_drug"] = { _Config_},
    ["other_drug"] = {_Config_}
}`

I did this for you, here is your config: https://pastebin.com/2iEtZgYa

Should be fine, but i can't check it out. The reason is that i don't develop with FiveM anymore ;)

Check it out and let me know is it work.

**Comment by crixzgamez** [comment] 2019-04-27 15:55
If all u did was add some closing brackets I have tried that already.
Damn thats a shame, love this script and really want it to work :(
ill try and use your config, but I doubt that will do the trick. 
You would make my world 10000 times better if u had time someday to look at it with me.

**Comment by MacieGx** [comment] 2019-04-27 15:59
Okay, i found where the problem is, let me some minutes i will make a other branch and make push in a few moments.

**Comment by MacieGx** [comment] 2019-04-27 16:09
> If all u did was add some closing brackets I have tried that already.
> Damn thats a shame, love this script and really want it to work :(
> ill try and use your config, but I doubt that will do the trick.
> You would make my world 10000 times better if u had time someday to look at it with me.

https://github.com/MacieGx/esx_planting/tree/test
Check it out, as i said i can't test it out bysalfe. You have to give me a reply, and send error logs when they will be ;)

**Comment by crixzgamez** [comment] 2019-04-27 16:28
It doesnt pin out any erros, but it doesnt start the process of planting the seed. We can talk on discord and look at it if u want?

**Comment by MacieGx** [comment] 2019-04-27 16:29
Sure, MacieG#0001

**Comment by crixzgamez** [comment] 2019-04-27 16:30
added u

**Comment by MacieGx** [comment] 2019-04-27 17:19
Fixed in: [Pull #3 ](https://github.com/MacieGx/esx_planting/pull/3)
Thanks @crixzgamez for cooperation! 💖

**Closed as completed by MacieGx** 2019-04-27 17:19 UTC

**Comment by LySoon** [comment] 2019-07-16 22:15
@MacieGx can you give me your discord too ? i have set up the config properly, there is no error on restart / start.. but i cant plant the second plant

im trying to add pumpkin right now.. and corn / wheat / etc stuff too if i can understand how it works ._.
bcs i dont have any errors in console
